### PR TITLE
Add a command that links to the docs

### PR DESCRIPTION
**Pull request by AlmostSuspense**
This PR adds a command similar to `.privacy` that sends the link to the official documentation (https://suggester.js.org/)

### CODE REVIEW

**Review by Benricheson101 — COMMENTED** [review]
Does this need its own command? The docs link is already in the help command https://github.com/Suggester/Suggester/blob/d482eeece5f38f57b634b5c21074103c9afc9a01/commands/other/help.js#L83

Other than that it looks good.

**Comment by AlmostSuspense** [comment]
the privacy policy was already linked in the help command before it became a command on its own, and i think having a quick way to send someone to the docs would be great

**Comment by Benricheson101** [comment]
Fair enough

**Review by Benricheson101 — APPROVED** [review]

**Comment by AlmostSuspense** [comment]
We're moving away from message-based commands in favor of slash commands so this isn't going to be merged

**Pull request closed without merging**
