### PR TITLE
Add guild name to various DM messages + minor typo fix

### PR DESCRIPTION
**Pull request by samsamson33**
This is mostly self-explanatory. I made the guild name bold where I added it. It's worth noting that I changed `showconfig` to be consistent with this. I put that change at the end intentionally so the commit could just be discarded if you didn't want it.

I also took the opportunity to change the capitalization in the `massapprove` and `massdelete` DM embed titles to be consistent with `approve` and `delete`, respectively.

### CODE REVIEW

**Comment by samsamson33** [comment]
This is a [suggestion in the suggestions channel](https://canary.discordapp.com/channels/566002482166104066/621433843294928927/651788417872560140), voted for 13 - 0. 
image

**Comment by Spammer2020** [comment]
Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020Spammer2020

**Review by BrightnessTM — CHANGES_REQUESTED** [review]
Everything added checks out and works, but for consistency the `config` command's `list` functionality should also bold the server name.

**Comment by samsamson33** [comment]
Fixed

**Review by BrightnessTM — APPROVED** [review]

**Pull request merged**
