### PR TITLE
Change README Discord badge for consistency

### PR DESCRIPTION
**Pull request by samsamson33**

### CODE REVIEW

**Comment by BrightnessTM** [comment]
Though this *is* consistent, does it look better?

**Review by Costpap — APPROVED** [review]
Personally speaking here, I find this badge to be better.

**Comment by AlmostSuspense** [comment]
Agreed, the blurple one looks better and is consistent with Discord's branding

**Comment by Costpap** [comment]
My comment was made in favor of @samsamson33's changes, which is also the reason that I have left a review **approving** these changes, in case you're replying to me, FYI.

**Comment by samsamson33** [comment]
The current one is also very pixelated for me. I'd assume that's just me though since some other people seem to like it more?
image

**Comment by BrightnessTM** [comment]
I hadn't noticed that before, the pixelation might make it worth changing

**Comment by samsamson33** [comment]
Yeah, I probably wouldn't have gone out of my way to change it if not for that, at least on my (1920×1080 with Windows 10 scaling) monitor, the current one looks outright *bad* (right next to the higher-quality ones at any rate).

**Pull request closed without merging**
